package cn.htwinkle.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	/**
	 * 配置id
	 */
	public M setConfigId(java.lang.Integer configId) {
		set("config_id", configId);
		return (M)this;
	}
	
	/**
	 * 配置id
	 */
	public java.lang.Integer getConfigId() {
		return getInt("config_id");
	}
	
	/**
	 * 配置名字
	 */
	public M setConfigName(java.lang.String configName) {
		set("config_name", configName);
		return (M)this;
	}
	
	/**
	 * 配置名字
	 */
	public java.lang.String getConfigName() {
		return getStr("config_name");
	}
	
	/**
	 * 配置值
	 */
	public M setConfigValue(java.lang.String configValue) {
		set("config_value", configValue);
		return (M)this;
	}
	
	/**
	 * 配置值
	 */
	public java.lang.String getConfigValue() {
		return getStr("config_value");
	}
	
	/**
	 * 类型
	 */
	public M setConfigType(java.lang.String configType) {
		set("config_type", configType);
		return (M)this;
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getConfigType() {
		return getStr("config_type");
	}
	
	/**
	 * 配置列
	 */
	public M setConfigTree(java.lang.String configTree) {
		set("config_tree", configTree);
		return (M)this;
	}
	
	/**
	 * 配置列
	 */
	public java.lang.String getConfigTree() {
		return getStr("config_tree");
	}
	
	/**
	 * 创建时间
	 */
	public M setConfigCreate(java.util.Date configCreate) {
		set("config_create", configCreate);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getConfigCreate() {
		return getDate("config_create");
	}
	
	/**
	 * 更新时间
	 */
	public M setConfigUpdate(java.util.Date configUpdate) {
		set("config_update", configUpdate);
		return (M)this;
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getConfigUpdate() {
		return getDate("config_update");
	}
	
}

