package cn.htwinkle.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExamAccount<M extends BaseExamAccount<M>> extends Model<M> implements IBean {

	/**
	 * 自增的id
	 */
	public M setAccountId(java.lang.Integer accountId) {
		set("account_id", accountId);
		return (M)this;
	}
	
	/**
	 * 自增的id
	 */
	public java.lang.Integer getAccountId() {
		return getInt("account_id");
	}
	
	/**
	 * 用户名
	 */
	public M setAccountName(java.lang.String accountName) {
		set("account_name", accountName);
		return (M)this;
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getAccountName() {
		return getStr("account_name");
	}
	
	/**
	 * 密码
	 */
	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 重要用户
	 */
	public M setAccountMain(java.lang.Integer accountMain) {
		set("account_main", accountMain);
		return (M)this;
	}
	
	/**
	 * 重要用户
	 */
	public java.lang.Integer getAccountMain() {
		return getInt("account_main");
	}
	
	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	/**
	 * 是否使用，1为使用
	 */
	public M setEnabled(java.lang.Integer enabled) {
		set("enabled", enabled);
		return (M)this;
	}
	
	/**
	 * 是否使用，1为使用
	 */
	public java.lang.Integer getEnabled() {
		return getInt("enabled");
	}
	
}

