package cn.htwinkle.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExamStatus<M extends BaseExamStatus<M>> extends Model<M> implements IBean {

	public M setStatusId(java.lang.Integer statusId) {
		set("status_id", statusId);
		return (M)this;
	}
	
	public java.lang.Integer getStatusId() {
		return getInt("status_id");
	}
	
	/**
	 * 用户
	 */
	public M setStatusUser(java.lang.Integer statusUser) {
		set("status_user", statusUser);
		return (M)this;
	}
	
	/**
	 * 用户
	 */
	public java.lang.Integer getStatusUser() {
		return getInt("status_user");
	}
	
	/**
	 * 任务
	 */
	public M setStatusTask(java.lang.Integer statusTask) {
		set("status_task", statusTask);
		return (M)this;
	}
	
	/**
	 * 任务
	 */
	public java.lang.Integer getStatusTask() {
		return getInt("status_task");
	}
	
	/**
	 * 任务状态
	 */
	public M setStatusContent(java.lang.String statusContent) {
		set("status_content", statusContent);
		return (M)this;
	}
	
	/**
	 * 任务状态
	 */
	public java.lang.String getStatusContent() {
		return getStr("status_content");
	}
	
	/**
	 * 补充说明
	 */
	public M setStatusRemarks(java.lang.String statusRemarks) {
		set("status_remarks", statusRemarks);
		return (M)this;
	}
	
	/**
	 * 补充说明
	 */
	public java.lang.String getStatusRemarks() {
		return getStr("status_remarks");
	}
	
	/**
	 * 任务创建时间
	 */
	public M setStatusCreate(java.util.Date statusCreate) {
		set("status_create", statusCreate);
		return (M)this;
	}
	
	/**
	 * 任务创建时间
	 */
	public java.util.Date getStatusCreate() {
		return getDate("status_create");
	}
	
}

