package cn.htwinkle.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExamTask<M extends BaseExamTask<M>> extends Model<M> implements IBean {

	public M setExamTaskId(java.lang.Integer examTaskId) {
		set("exam_task_id", examTaskId);
		return (M)this;
	}
	
	public java.lang.Integer getExamTaskId() {
		return getInt("exam_task_id");
	}
	
	/**
	 * 任务名称
	 */
	public M setExamTaskName(java.lang.String examTaskName) {
		set("exam_task_name", examTaskName);
		return (M)this;
	}
	
	/**
	 * 任务名称
	 */
	public java.lang.String getExamTaskName() {
		return getStr("exam_task_name");
	}
	
	/**
	 * 是否使用，1为使用
	 */
	public M setExamTaskEnabled(java.lang.Integer examTaskEnabled) {
		set("exam_task_enabled", examTaskEnabled);
		return (M)this;
	}
	
	/**
	 * 是否使用，1为使用
	 */
	public java.lang.Integer getExamTaskEnabled() {
		return getInt("exam_task_enabled");
	}
	
	public M setExamTaskCreate(java.util.Date examTaskCreate) {
		set("exam_task_create", examTaskCreate);
		return (M)this;
	}
	
	public java.util.Date getExamTaskCreate() {
		return getDate("exam_task_create");
	}
	
}

