version: "3"

services:
  htwinkle.cn.web:
    image: registry.cn-hangzhou.aliyuncs.com/htwinkle/htwinkle.cn.web
    container_name: htwinkle.cn.web
    ports:
      - "9011:9011"
    environment:
      - "TZ=Asia/Shanghai"
      - "LANG=en_US.UTF-8"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    volumes:
      - "/opt/htwinkle.cn.web/web/log/:/opt/hwinkle.cn.web/web/log/"
      - "/opt/htwinkle.cn.web/web/backUpFile/:/opt/htwinkle.cn.web/web/backUpFile/"