package cn.htwinkle.web.model;

import cn.htwinkle.web.model.base.BaseExamAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamAccount extends BaseExamAccount<ExamAccount> {
	public static final ExamAccount dao = new ExamAccount().dao();
}

