package cn.htwinkle.web.model;

import cn.htwinkle.web.model.base.BaseExamStatus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamStatus extends BaseExamStatus<ExamStatus> {
	public static final ExamStatus dao = new ExamStatus().dao();
}

