package cn.htwinkle.web.model;

import cn.htwinkle.web.model.base.BaseExamTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamTask extends BaseExamTask<ExamTask> {
	public static final ExamTask dao = new ExamTask().dao();
}

