name: htwinkle.web - deploy

on:
  push:
    branches: [ develop ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
         distribution: 'adopt'
         java-version: '8'
      - uses: stCarolas/setup-maven@v4
        with:
         maven-version: 3.5.4
         
      - name: show dir
        run: ls
        
      - name: package
        run: mvn clean package

