name: htwinkle.web - deploy

on:
  push:
    branches: [ develop ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
         distribution: 'adopt'
         java-version: '8'
      - uses: stCarolas/setup-maven@v4
        with:
         maven-version: 3.5.4
         
      - name: show dir
        run: ls
        
      - name: package
        run: mvn clean package
        
      - name: show package dir
        run: ls  
        
      - name: stop service app
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          run: |
              echo 'stop server'
              cd /root/app_web/htwinkle.cn.web/web
              ls
              ./runServer.sh stop
              
      - name: delete service dir
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          run: |
              rm -rf /root/app_web_htwinkle.cn.web/web

      - name: upload to server
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          local: "./target/web-release*/web"
          remote: "/root/app_web/app_web_htwinkle.cn/"
          
      - name: chmod shell file
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          run: |
              cd /root/app_web/htwinkle.cn.web/web
              chmod +755 runServer.sh
              
      - name: start server
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          run: |
              cd /root/app_web/htwinkle.cn.web/web
              ./runServer.sh start              
      
        
        

