name: htwinkle.web - deploy

on:
  push:
    branches: [ develop ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
         distribution: 'adopt'
         java-version: '8'
      - uses: stCarolas/setup-maven@v4
        with:
         maven-version: 3.5.4
         
      - name: show dir
        run: ls
        
      - name: package
        run: mvn clean package
        
      - name: show package dir
        run: ls  
        
      - name: stop server
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          script: |
              docker rm -f htwinkle.cn.web     
        
              
      - name: delete server dir
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          script: |
              rm -rf /home/app/htwinkle.cn.web/web

      - name: upload to server
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          local: "./target/web-release*/web"
          remote: "/home/app/htwinkle.cn.web/"
          
      - name: chmod shell file
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          script: |
              cd /root/app_web/htwinkle.cn.web/web
              chmod +755 runServer.sh
              
      - name: start server
        uses: tarunjangra/ssh-remote-cmd@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          command: |
            docker run -p 9011:9011 --name jdk1.8 \
                --network host \
                -v /home/app/htwinkle.cn.web/:/home \
                -d -it majiajue/jdk1.8
            docker exec -it jdk1.8 /bin/bash
            cd /home/web/ && ./runServer.sh start
      
        
        

